name : CI/CD Pipeline for SharePoint 2019
Env: OUTPUT_PATH: ${{ github.workspace }}
on : [push]

jobs:
# Deploy VM in Azure
  DepoyVM:
    runs-on : windows-latest

steps:
# checkout code from repo
- name: checkout repo
  uses : actions/checkout

- name: look for ps1 file
  run: |
  ls '${{ env.OUTPUT_PATH }}\IaC\AzCLI'

- name : provision virtual machine in azure
  env:
    RESOURCE_GROUP: rg-githubitpro
    RESOURCE_GROUP_REGION: southcentralus
    SERVER_NAME: githubactions
    ADMIN_LOGIN: swapz17

  run: >
    powershell -command "& '${{ env.OUTPUT_PATH }}\IaC\AzCLI\vmcreation.ps1'"
    -servicePrincipal ${{ secrets.SERVICE_PRINCIPAL_APPID }}
    -servicePrincipalSecret ${{ secrets.SERVICE_PRINCIPAL_SECRET }}
    -servicePrincipalTenantID ${{ secrest.SERVICE_PRINCIPAL_TENANTID}}
    -azureSunscriptionName ${{ secrest.AZURE_SUBSCRIPTION_ID}}
    -resourceGroupName %RESOURCE_GROUP%
    -resourceGroupRegion %RESOURCE_GROUP_REGION%
    -serverName %SERVER_NAME%
    -adminLogin %ADMIN_LOGIN%
    -adminPassword ${{ secrets.ADMIN_PASSWORD}}

