# This is a basic workflow to help you get started with Actions

name: CI/CD Pipeline for SharePoint 2019

env: 
  OUTPUT_PATH: ${{ github.workspace }}
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Deploy VM in Azure
  DeployVM:
    runs-on : windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # checkout code from repo
      - name: checkout repo
        uses : actions/checkout@v1

      - name: look for ps1 file
        run: |
          ls '${{ env.OUTPUT_PATH }}\IaC\AzCLI'

      - name : provision virtual machine in azure
        env:
          RESOURCE_GROUP: rg-githubitpro
          RESOURCE_GROUP_REGION: southcentralus
          SERVER_NAME: githubactions
          ADMIN_LOGIN: swapz17
        run: >
          powershell -command "& '${{ env.OUTPUT_PATH }}\IaC\AzCLI\vmcreation.ps1'"
          -servicePrincipal ${{ secrets.SERVICE_PRINCIPAL_APPID }}
          -servicePrincipalSecret ${{ secrets.SERVICE_PRINCIPAL_SECRET }}
          -servicePrincipalTenantID ${{ secrets.SERVICE_PRINCIPAL_TENANTID}}
          -azureSunscriptionName ${{ secrest.AZURE_SUCRIPTION_ID}}
          -resourceGroupName %RESOURCE_GROUP%
          -resourceGroupRegion %RESOURCE_GROUP_REGION%
          -serverName %SERVER_NAME%
          -adminLogin %ADMIN_LOGIN%
          -adminPassword ${{ secrets.ADMIN_PASSWORD}}